# Generated by Django 4.1 on 2022-10-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_man', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryman',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='lat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='long',
            field=models.IntegerField(default=0),
        ),
    ]
