# Generated by Django 4.1 on 2022-10-23 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery_man', '0002_alter_deliveryman_last_update_alter_deliveryman_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField()),
                ('delivery_lat', models.IntegerField()),
                ('delivery_long', models.IntegerField()),
                ('destination_lat', models.IntegerField()),
                ('destination_long', models.IntegerField()),
                ('delivery_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_man.deliveryman')),
            ],
        ),
    ]
