# Generated by Django 4.1 on 2022-10-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField()),
                ('delivery_lat', models.IntegerField()),
                ('delivery_long', models.IntegerField()),
                ('destination_lat', models.IntegerField()),
                ('destination_long', models.IntegerField()),
            ],
        ),
    ]
