name: Testing delivery app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 3
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: delivery
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      env:
        DJANGO_ALLOWED_HOSTS: localhost
    - name: Run tests
      run: python manage.py test
      env:
        DEBUG: "0"
        DJANGO_ALLOWED_HOSTS: localhost
        DB_ENGINE: django.db.backends.postgresql
        DB_HOST: localhost
        DB_DATABASE: delivery
        DB_USER: postgres
        DB_PASSWORD: postgres
